# SPDX-License-Identifier: GPL-2.0-only
CFLAGS += -I../../../../../usr/include/
CFLAGS += -I../../../../../include/uapi/

TEST_GEN_PROGS := afu_intr

top_srcdir ?=../../../../..

include ../../lib.mk
