# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2020-2022 Xilinx, Inc. All rights reserved.
#
# Authors: Sonal.Santan@xilinx.com
#          Lizhi.Hou@xilinx.com
#

obj-$(CONFIG_FPGA_XRT_XMGMT) += xrt-mgmt.o

xrt-mgmt-objs :=		\
	xmgmt-drv.o
